name: Publish Docs
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - run: npx typedoc --theme ./node_modules/typedoc-deno-theme/ index.d.ts
      - run: mv docs docs.new
  public-docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: git checkout gh-pages
      - run: rm -rf docs
      - run: mv docs.new docs
      - run: git add docs
      - run: "git commit -m 'docs: update'"
      - run: git push origin gh-pages
      - run: git checkout main


